require_relative '../lib/cli.rb'
require_relative '../lib/recipe.rb'
require_relative '../lib/scraper.rb'
require_relative '../lib/difficulty.rb'
require_relative '../lib/time.rb'
require_relative '../lib/vegetarian.rb'
require_relative '../lib/menu_options/random_recipes.rb'
require_relative '../lib/menu_options/choose_from_all.rb'
require_relative '../lib/menu_options/list_all_dishes.rb'
require_relative '../lib/menu_options/menu.rb'
require_relative '../lib/menu_options/choose_by_difficulty.rb'
require_relative '../lib/menu_options/choose_by_cooking_time.rb'
require_relative '../lib/menu_options/choose_from_veggie_options.rb'

# require_all '../lib'